kind: pipeline
type: docker
name: build

platform:
  os: linux
  arch: amd64

steps:

## Run the fips (debug) unittest endpoint
- name: build-fips-unittest
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-unittest
    - ./fips build

## Run the release inittest endpoint
- name: build-fips-release
  image: amarburg/lsdslam-dev-host
  commands:
    - ./fips set config linux-make-release-unittest
    - ./fips build

## Build with ROS melodic
- name: build-ros-melodic
  image: amarburg/drone-ci-ros:melodic
  commands:
    - wget -O- https://gitlab.com/amarburg/ros_drone_ci/-/raw/master/bootstrap.sh | /bin/bash
  environment:
    ROS_PACKAGES_TO_INSTALL: cv-bridge image-transport opencv-apps
    WSTOOL_RECURSIVE: true

## On success, trigger a rebuild of oculus_sonar_ros
- name: trigger-gitlab-downstream
  image: plugins/downstream
  settings:
    server: https://gitlab.drone.camhd.science
    fork: true
    token:
      from_secret: gitlab_drone_token
    repositories:
      - apl-ocean-engineering/oculus_sonar_ros

## _and_ serdp_player
- name: trigger-github-downstream
  image: plugins/downstream
  settings:
    server: https://github.drone.camhd.science
    fork: true
    token:
      from_secret: github_drone_token
    repositories:
      - apl-ocean-engineering/serdp_player

- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: slack_webhook
  when:
    status: [ success, failure ]
